[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PyJuliaMPBSolver"
version = "0.1.0"
authors = [
	{name = "Jason Landini", email = "landinjm@umich.edu"},
]
description = "Python wrapper for JuliaMPBSolver"
requires-python = ">=3.9"
dependencies = [
	"numpy>=1.20.0,<2.0.0",
	"juliacall>=0.9.0"
]

